### ISSUE TITLE
making request to eve, previous value cached in browser. how to prevent restangular getlist query caching?

### ISSUE THREAD

**Issue by satyanani40** [WebSoc/lunar-cloud#15]
Clear browser cache or pressing ctrl+f5 cache was clearing, and then making new request getting perfect result. How to overcome this problem?

**Comment by ratanraj** [comment]
http://example.com/test?seed=Math.random()

**Comment by ratanraj** [comment]
http://arusahni.net/blog/2014/03/flask-nocache.html

**Comment by satyanani40** [comment]
its working. thanks bro
